# Generated by Django 4.2 on 2023-05-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_uz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Natijalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol_id', models.IntegerField()),
                ('savol', models.TextField()),
                ('javob', models.IntegerField()),
                ('tg_id', models.IntegerField()),
                ('tur', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Natijalarru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol_id', models.IntegerField()),
                ('savol', models.TextField()),
                ('javob', models.IntegerField()),
                ('tg_id', models.IntegerField()),
                ('turru', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_savollar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('variant1', models.TextField()),
                ('variant2', models.TextField()),
                ('variant3', models.TextField()),
                ('variant4', models.TextField()),
                ('tur', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test_savollarru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('variant1', models.TextField()),
                ('variant2', models.TextField()),
                ('variant3', models.TextField()),
                ('variant4', models.TextField()),
                ('turru', models.CharField(max_length=30)),
            ],
        ),
    ]
